### ISSUE TITLE
[Ubuntu22.04] AttributeError: 'PosixPath' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by HopeCollector** [maschere/pyjop#1]
# Enviroment

OS: Ubuntu22.04
CPU: x86_64
Python: 3.10.12

# Waht happened

python gave me these message when doing "from pyjop import *"

```shell
....Initializing JOY OF PROGRAMMING Python process.......Traceback (most recent call last):
  File "/usr/lib/python3.10/pkgutil.py", line 417, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/home/lawskiy/.venvs/pyjop/lib/python3.10/site-packages/pyjop')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lawskiy/workspace/jop_ws/./test.py", line 1, in <module>
    from pyjop import *
  File "/home/lawskiy/.venvs/pyjop/lib/python3.10/site-packages/pyjop/__init__.py", line 54, in <module>
    for _, __module_name_it, _ in iter_modules([__package_dir]):
  File "/usr/lib/python3.10/pkgutil.py", line 129, in iter_modules
    for i in importers:
  File "/usr/lib/python3.10/pkgutil.py", line 421, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1632, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1504, in __init__
  File "<frozen importlib._bootstrap_external>", line 182, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'
```

# How to reproduce this problem

1. create virtual env & activate it
2. install package

```shell
pip install git+https://github.com/maschere/pyjop -U --no-cache-dir
```
3. create a test.py with this command
```shell
echo "from pyjop import *" > ./test.py
```
4. run the file
```shell
python3 ./test.py
```

**Comment by HopeCollector** [comment]
https://github.com/maschere/pyjop/blob/550a9128b9f854308813e8ba6a4a74150fef9622/pyjop/__init__.py#L53

can we use os.path instead?

```python
__package_dir = os.path.abspath(os.path.join(__file__, ".."))
```

works fine on Ubuntu22.04 & Win11 23H2
